# fly.toml app configuration file generated for fast-zero-twilight-smoke-2104-v1 on 2024-08-08T22:24:02-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fast-zero-twilight-smoke-2104-v1'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
