"""Add created_at and updated_at columns to todos

Revision ID: fdd4d4562f8c
Revises: 807ac2c2f900
Create Date: 2024-08-04 20:24:03.670730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd4d4562f8c'
down_revision: Union[str, None] = '807ac2c2f900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
